---

- name: set OS dependent variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_facts.distribution }}.yaml'
    - '{{ ansible_facts.os_family }}.yaml'

- name: set OS dependent tasks
  ansible.builtin.include_tasks: '{{ item }}'
  with_first_found:
    - '{{ ansible_facts.distribution }}.yaml'
    - '{{ ansible_facts.os_family }}.yaml'
